# Generated by Django 5.0.6 on 2025-02-10 09:12

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Birlik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Kategoriya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[('admin', 'Admin'), ('diller', 'Diller'), ('sotuv_agent', 'Sotuv Agent'), ('klient', 'Klient')], default='klient', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=255, unique=True)),
                ('narx', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rasm', models.ImageField(blank=True, null=True, upload_to='mahsulotlar/')),
                ('birlik', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='all.birlik')),
                ('kategoriya', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='all.kategoriya')),
            ],
        ),
        migrations.CreateModel(
            name='Ombor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('responsible_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_warehouses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField()),
                ('yetkazib_beruvchi', models.CharField(max_length=255)),
                ('status', models.CharField(default='Yaratilgan', max_length=50)),
                ('total_sum', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ombor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all.ombor')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soni', models.PositiveIntegerField()),
                ('narx', models.DecimalField(decimal_places=2, max_digits=10)),
                ('yaroqlilik_muddati', models.DateField(blank=True, null=True)),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all.mahsulot')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='all.purchase')),
            ],
        ),
        migrations.CreateModel(
            name='Sotuv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField()),
                ('total_sum', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('from_ombor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sotuvlar_chiqish', to='all.ombor')),
                ('sotib_oluvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('to_ombor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sotuvlar_kirish', to='all.ombor')),
            ],
        ),
        migrations.CreateModel(
            name='Qarz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qarz_summasi', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tolangan_summa', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sana', models.DateField(auto_now_add=True)),
                ('eslatma', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qarzlari', to=settings.AUTH_USER_MODEL)),
                ('sotuv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qarzlari', to='all.sotuv')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField()),
                ('summa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sotuv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='all.sotuv')),
            ],
        ),
        migrations.CreateModel(
            name='SotuvItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soni', models.PositiveIntegerField()),
                ('narx', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all.mahsulot')),
                ('sotuv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='all.sotuv')),
            ],
        ),
        migrations.CreateModel(
            name='OmborMahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soni', models.PositiveIntegerField(default=0)),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all.mahsulot')),
                ('ombor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all.ombor')),
            ],
            options={
                'unique_together': {('ombor', 'mahsulot')},
            },
        ),
    ]
